name: Build & deploy release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set pom version to release
        id: pom
        run: |
          mvn -B versions:set -DremoveSnapshot=1

          JAR=$(mvn -q git-commit-id:revision help:evaluate -DforceStdout -Dexpression=project.build.finalName).jar
          echo "JAR=$JAR" >> $GITHUB_ENV

          VERSION=$(mvn -q help:evaluate -DforceStdout -Dexpression=project.version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          git commit -m "Release $VERSION" -a
      - name: Build & deploy to Nexus
        env:
          NEXUS_USER: ci
          NEXUS_PASS: ${{ secrets.NEXUS_CI }}
        run: mvn --batch-mode --update-snapshots --settings deploy.xml deploy
      - name: Push to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft release
        id: draft_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$VERSION
          release_name: Build $VERSION
          draft: true
          prerelease: false
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./target/$JAR
          asset_name: $JAR
          asset_content_type: application/java-archive
